name: Call a reusable workflow and use its outputs

on:
  issue_comment:
    types: [created]

  pull_request:
    paths:
      - 'arg/dev/**'
      - 'arg/stage/**'
      - 'arg/prod/**'

  
 
jobs:

  Deploy:
    

    uses: Bancar/uala-infrastructure-reusable-workflows/.github/workflows/all_deployment_app.yaml@main

    with:
      TERRAFORM_VERSION: '1.1.9'
      TERRAGRUNT_VERSION: '0.36.9'
      TERRAGRUNT_ACTION_VERSION: 'v5.0.0'
      ENVIRONMENTS: '"dev","stage","prod"'
      COUNTRIES: '"arg"'
      OIDC: true
      VPN: false
    
    secrets: 
      OIDC_ASSUME_ROLE: 
      UALA_GLOBAL_SSH_KEY: 
      GH_APP_INSTALATION_ID: 
      GH_APP_ID: 
      APP_BANCAR_SSH_KEY : 